[application]
name = "xen-fret"
default_platform = "web"

[bundle]
title = "Xen Fret"
identifier = "io.github.sintrastes.xenfret"
publisher = "Nathan Bedell"
icon = [
    "assets/icons/icon-32.png",
    "assets/icons/icon-128.png",
    "assets/icons/icon-256.png",
    "assets/icons/icon.icns",
]

[web.app]
title = "Xen Fret"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource.dev]
style = ["/assets/base.css", "/assets/web.css"]
script = []

[web.resource.release]
style = ["/assets/base.css", "/assets/web.css"]
script = []
