
module XenFret.Sagittal where

-- Quarter tone accidentials
quarterToneFlat        = T.pack [chr 0xE280]
quarterToneSharp       = T.pack [chr 0xE282]
threeQuarterTonesFlat  = T.pack [chr 0xE281]
threeQuarterTonesSharp = T.pack [chr 0xE283]

-- Spartan single shaft accidentals
sagittal5v7KleismaUp       = T.pack [chr 0xE300]
sagittal5CommaUp           = T.pack [chr 0xE302]
sagittal7CommaUp           = T.pack [chr 0xE304]
sagittal25SmallDiesisUp    = T.pack [chr 0xE306]
sagittal35MediumDiesisUp   = T.pack [chr 0xE308]
sagittal11MediumDiesisUp   = T.pack [chr 0xE30A]
sagittal11LargeDiesisUp    = T.pack [chr 0xE30C]
sagittal35LargeDiesisUp    = T.pack [chr 0xE30E]
sagittal5v7KleismaDown     = T.pack [chr 0xE301]
sagittal5CommaDown         = T.pack [chr 0xE303]
sagittal7CommaDown         = T.pack [chr 0xE305]
sagittal25SmallDiesisDown  = T.pack [chr 0xE307]
sagittal35MediumDiesisDown = T.pack [chr 0xE309]
sagittal11MediumDiesisDown = T.pack [chr 0xE30B]
sagittal11LargeDiesisDown  = T.pack [chr 0xE30D]
sagittal35LargeDiesisDown  = T.pack [chr 0xE30F]

-- Spartan multi shaft accidentals
sagittalSharp25SDown        = T.pack [chr 0xE310] 
sagittalSharp7CDown         = T.pack [chr 0xE312]
sagittalSharp5CDown         = T.pack [chr 0xE314]
sagittalSharp5v7kDown       = T.pack [chr 0xE316]
sagittalSharp               = T.pack [chr 0xE318]
sagittalSharp5v7kUp         = T.pack [chr 0xE31C]
sagittalSharp5CUp           = T.pack [chr 0xE31E]
sagittalSharp7CUp           = T.pack [chr 0xE320]
sagittalSharp25SUp          = T.pack [chr 0xE322]
sagittalSharp35MUp          = T.pack [chr 0xE324]
sagittalSharp11MUp          = T.pack [chr 0xE326]
sagittalSharp11LUp          = T.pack [chr 0xE328]
sagittalSharp35LUp          = T.pack [chr 0xE32A]
sagittalDoubleSharp25SDown  = T.pack [chr 0xE32C]
sagittalDoubleSharp7CDown   = T.pack [chr 0xE32E]
sagittalDoubleSharp5CDown   = T.pack [chr 0xE330]
sagittalDoubleSharp5v7kDown = T.pack [chr 0xE332]
sagittalDoubleSharp         = T.pack [chr 0xE334]
sagittalFlat25SUp           = T.pack [chr 0xE311]
sagittalFlat7CUp            = T.pack [chr 0xE313]
sagittalFlat5CUp            = T.pack [chr 0xE315]
sagittalFlat5v7kUp          = T.pack [chr 0xE317]
sagittalFlat                = T.pack [chr 0xE319]
sagittalFlat5v7kDown        = T.pack [chr 0xE31D]
sagittalFlat5CDown          = T.pack [chr 0xE31F]
sagittalFlat7CDown          = T.pack [chr 0xE321]
sagittalFlat25SDown         = T.pack [chr 0xE323]
sagittalFlat35MDown         = T.pack [chr 0xE325]
sagittalFlat11MDown         = T.pack [chr 0xE327]
sagittalFlat11LDown         = T.pack [chr 0xE329]
sagittalFlat35LDown         = T.pack [chr 0xE32B]
sagittalDoubleFlat25SUp     = T.pack [chr 0xE32D]
sagittalDoubleFlat7CUp      = T.pack [chr 0xE32F]
sagittalDoubleFlat5CUp      = T.pack [chr 0xE331]
sagittalDoubleFlat5v7kUp    = T.pack [chr 0xE333]
sagittalDoubleFlat          = T.pack [chr 0xE335]