name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          sandbox = true
          binary-caches = https://cache.nixos.org https://nixcache.reflex-frp.org
          binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=
          binary-caches-parallel-connections = 40
    - name: Build webapp with nix
      run: |
        nix-build --show-trace -A ghcjs.frontend -o result
        tar -cvzf xen-fret-js-frontend.tar.gz result/*
    - name: Build Android app with nix
      run: |
        nix-build -A android.frontend -o result-android
        ls result-android
        cp result-android/android-app-debug.apk ./xen-fret-android-app.apk
    - name: Archive webapp
      uses: actions/upload-artifact@v2
      with:
        name: ghcjs-frontend
        path: xen-fret-js-frontend.tar.gz
    - name: Archive Android app
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: xen-fret-android-app.apk